import {
  AboutPage,
  AccessoriesBagsPage,
  AccessoriesCategoryPage,
  AccessoriesGlassesPage,
  ContactsPage,
  FootwearCategoryPage,
  FootwearShoesPage,
  FootwearSneakersPage,
  LoginPage,
  MainPage,
  MenCategoryPage,
  MenSweatshirtsPage,
  MenTrousersPage,
  Page404,
  ShopPage,
  SignupPage,
  UserProfilePage,
  WomenCategoryPage,
  WomenDressesPage,
  WomenTrousersPage,
} from '../../../pages';

export const pages = [
  { id: 1, page: MainPage, path: '/' },
  { id: 2, page: AboutPage, path: '/about' },
  { id: 3, page: ContactsPage, path: '/contacts' },
  { id: 4, page: LoginPage, path: '/login' },
  { id: 5, page: ShopPage, path: '/shop' },
  { id: 6, page: SignupPage, path: '/signup' },
  { id: 7, page: WomenCategoryPage, path: '/shop/women' },
  { id: 8, page: MenCategoryPage, path: '/shop/men' },
  { id: 9, page: FootwearCategoryPage, path: '/shop/footwear' },
  { id: 10, page: AccessoriesCategoryPage, path: '/shop/accessories' },
  { id: 11, page: WomenTrousersPage, path: '/shop/women/trousers' },
  { id: 12, page: WomenDressesPage, path: '/shop/women/dresses' },
  { id: 13, page: MenTrousersPage, path: '/shop/men/trousers' },
  { id: 14, page: MenSweatshirtsPage, path: '/shop/men/sweatshirts' },
  { id: 14, page: FootwearShoesPage, path: '/shop/footwear/shoes' },
  { id: 15, page: FootwearSneakersPage, path: '/shop/footwear/sneakers' },
  { id: 16, page: AccessoriesGlassesPage, path: '/shop/accessories/glasses' },
  { id: 17, page: AccessoriesBagsPage, path: '/shop/accessories/bags' },
  { id: 18, page: UserProfilePage, path: '/user' },
  { id: 19, page: Page404, path: '*' },
];
