export { AboutPage } from './AboutPage';
export { ContactsPage } from './ContactsPage';
export { LoginPage } from './LoginPage';
export { MainPage } from './MainPage';
export { Page404 } from './Page404';
export { ProductPage } from './ProductPage';
export { ShopPage } from './ShopPage';
export { SignupPage } from './SignupPage';
export { UserProfilePage } from './UserProfilePage';
